version: "3"
networks:
  banco:
    driver: bridge
  sistema:
  host:
services:
  # db:
  #   image: postgres:9.6
  #   environment:
  #     POSTGRES_USER: "postgres"
  #     POSTGRES_PASSWORD: "postgres"
  #     # - POSTGRES_DB= teste
  #     # - POSTGRES_HOST_AUTH_METHOD= trust
  #   volumes:
  #     - dados:/var/lib/postgresql/data
  #     - ./scripts:/scripts
  #     - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
  #   # - ./data:/var/lib/postgresql/data
  #   networks:
  #     - banco
  #   ports:
  #     - 15432:5432

  # pgadmin:
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: "roger.peratello@hotmail.com"
  #     PGADMIN_DEFAULT_PASSWORD: "admin"
  #   ports:
  #     - 90:80
  #   depends_on:
  #     - db
  #   networks:
  #     - banco

  # frontend:
  #   image: nginx:1.13
  #   volumes:
  #     # Site
  #     - ./web:/usr/share/nginx/html/
  #     # Configuração do Proxy Reverso
  #     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  #   ports:
  #     - 81:80
  #   networks:
  #     - web
  #   depends_on:
  #     - app

  main:
    image: prsmain
    volumes:
      - ./cnsettings.json:/app/cnsettings.json
    ports: 
      - 53300:80
    networks:
      - host

  collector:
    image: prscollector
    volumes:
      - ./cnsettings.json:/app/cnsettings.json
      - ./dbsettings.json:/app/dbsettings.json
    ports: 
      - 53306:80
    networks:
      - host
